# site name
prefixName: さくら荘の
siteName: ましろ
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/Avatar.png
url: https://mashiro.fun/
description: Hi Mashiro
cdn: https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr@v1.6
pjax: 1
# 1开启
mathjax: 0

notice: 空太是笨蛋
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    极客: {path: /categories/极客/, fa: fa-code },
    余念: {path: /categories/余念/, fa: fa-send-o },
#    资源: {path: /categories/资源/, fa: fa-cloud-download },
#    随想: {path: /categories/随想/, fa: fa-commenting-o },
#    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
 #   书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
    番剧: {path: /bangumi/, fa: fa-film faa-vertical },
    音乐: {path: /music/, fa: fa-music },
 #   图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /about/, fa: fa-leaf faa-wrench
#    我？: {path: /about/, fa: fa-meetup},
#    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
#    Lab: {path: /lab/, fa: fa-cogs },
  }
# 客户端: { path: /client/, fa: fa-android faa-vertical }
#  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr/img/cover/fm1.jpg
  - https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr/img/cover/fm2.jpg
  - https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr/img/cover/fm3.jpg
  - https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr/img/cover/fm4.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /, title: Sakura, desc: 解锁中ing, img: /img/startdash/st1.png}
  - {url: https://space.bilibili.com/253963832, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/st2.jpg}
  - {url: /, title: Mashiro的万事屋, desc: 解锁中ing, img: /img/startdash/st3.jpg}



# your site build time or founded date
siteBuildingTime: 11/19/2019

#social  url, img PC端配置
social:
  github: {url: https://github.com/MashiroRb, img: /img/social/github.png}
  bilibili: {url: https://space.bilibili.com/253963832, img: /img/social/bilibili.png}
  wangyiyun: {url: https://music.163.com/user/home?id=504522476, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/feng-ji-xu-chui-37-87, img: /img/social/zhihu.png}
#  email: {url: https://github.com/MashiroRb, img: /img/social/email.svg}
# wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
#  github: {url: https://github.com/MashiroRb, fa: fa-github, color: 333}
#  bilibili: {url: https://space.bilibili.com/253963832, img: /img/social/bilibili.png}
#  wangyiyun: {url: https://music.163.com/user/home?id=504522476, img: /img/social/wangyiyun.png}
#  zhihu: {url: https://www.zhihu.com/people/feng-ji-xu-chui-37-87, img: /img/social/zhihu.png}
  
donate:
  alipay: /img/custom/donate/AliPayQR.png
  wechat: /img/custom/donate/WechanQR.png
  wechatSQ: /img/custom/donate/WechanSQ.png

# 视频地址为https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr@v1.0/DSHH.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/MashiroRb/CDNjsDelivr@v1.0
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: DSHH.mp4

aplayer: 
  id: 2899922295
  server: netease
  type: playlist
  fixed: true
  mini: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: oQaTHxPDbuLGPYTWCef4ci6y-gzGzoHsz
v_appKey: FhBzUx0axroBJj1WBn62hyHS
